services: 
  - docker

before_install:
  - docker build -t andi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andi/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  # edge: true # Enables dpl v.2. If you don`t select this line the deployment on travisci will fail
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-715841334298"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY_ID" # updated
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  dpl_version: 1.10.16
