# This file will connect the GitHub with TravisCI. 
sudo: required
services: 
  - docker
before_install:
  - docker build -t andi/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true andi/docker-react npm run test 
  # Deploy Elastic Beanstalk to AWS
deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-715841334298"
  bucket_path: "frontend"
  on:
     branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY" 

